r"""Tests for ekdist.resolution.impose_resolution.

Numerical regression values for AChsim.scn (tres=30 µs) were generated by
running our Python impose_resolution on 2026-06-04 and pinned as golden-master
references.  The Fortran EKDIST program (E:\dcprogs\dcdos\ekdist.exe) is a
16-bit DOS executable that cannot be run directly on 64-bit Windows; a DOSBox
comparison remains a future TODO.
"""

import numpy as np
import numpy.testing as npt
import pytest

from ekdist.resolution import impose_resolution


# =========================================================================== #
# Input validation                                                              #
# =========================================================================== #

class TestInputValidation:
    def test_mismatched_lengths_raises(self):
        with pytest.raises(ValueError, match="same length"):
            impose_resolution(
                np.array([0.1, 0.2]), np.array([1.0]), np.array([0, 0]), tres=0.0
            )

    def test_empty_arrays_raises(self):
        with pytest.raises(ValueError, match="empty"):
            impose_resolution(
                np.array([]), np.array([]), np.array([]), tres=0.0
            )

    def test_negative_tres_raises(self):
        with pytest.raises(ValueError, match="non-negative"):
            impose_resolution(
                np.array([0.1]), np.array([1.0]), np.array([0]), tres=-1.0
            )

    def test_no_resolvable_intervals_raises(self):
        # tres larger than all intervals → nothing resolvable
        with pytest.raises(ValueError, match="No resolvable"):
            impose_resolution(
                np.array([0.001, 0.001]),
                np.array([1.0, 0.0]),
                np.array([0, 0]),
                tres=0.01,
            )

    def test_all_bad_flags_raises(self):
        with pytest.raises(ValueError, match="No resolvable"):
            impose_resolution(
                np.array([0.1, 0.05]),
                np.array([1.0, 0.0]),
                np.array([8, 8]),  # all unusable
                tres=0.001,
            )


# =========================================================================== #
# Structural properties (hold for any valid record)                            #
# =========================================================================== #

class TestStructuralProperties:
    def test_result_starts_with_open(self, simple_intervals):
        itint, iampl, iprop = simple_intervals
        rtint, rampl, rprop = impose_resolution(itint, iampl, iprop, tres=0.001)
        assert len(rampl) > 0
        assert rampl[0] != 0.0, "First resolved interval must be an opening"

    def test_result_ends_with_open(self, simple_intervals):
        itint, iampl, iprop = simple_intervals
        rtint, rampl, rprop = impose_resolution(itint, iampl, iprop, tres=0.001)
        assert rampl[-1] != 0.0, "Last resolved interval must be an opening"

    def test_no_negative_durations(self, simple_intervals):
        itint, iampl, iprop = simple_intervals
        rtint, rampl, rprop = impose_resolution(itint, iampl, iprop, tres=0.001)
        assert np.all(rtint >= 0), "All resolved durations must be non-negative"

    def test_resolution_reduces_interval_count(self):
        """After tres > 0, resolved count must be < raw count."""
        itint = np.array([0.05, 0.0005, 0.08, 0.04])
        iampl = np.array([1.0, 0.0, 1.0, 0.0])
        iprop = np.array([0, 0, 0, 0])
        rtint, rampl, rprop = impose_resolution(itint, iampl, iprop, tres=0.001)
        assert len(rtint) <= len(itint)

    def test_zero_resolution_preserves_structure(self):
        """tres=0 should resolve all intervals (none concatenated)."""
        itint = np.array([0.05, 0.02, 0.08, 0.03])
        iampl = np.array([1.0, 0.0, 1.0, 0.0])
        iprop = np.array([0, 0, 0, 0])
        rtint, rampl, rprop = impose_resolution(itint, iampl, iprop, tres=0.0)
        # Two opens, two shuts; after trimming trailing shut: 3 resolved
        assert len(rtint) == 3
        assert rampl[0] != 0.0
        assert rampl[1] == 0.0
        assert rampl[2] != 0.0


# =========================================================================== #
# Specific known-input → known-output cases                                    #
# =========================================================================== #

class TestKnownOutputs:
    def test_single_open_period(self, single_open_record):
        """[open 100ms, shut 50ms] → one 100ms open period after resolution."""
        itint, iampl, iprop = single_open_record
        rtint, rampl, rprop = impose_resolution(itint, iampl, iprop, tres=0.001)
        assert len(rtint) == 1
        npt.assert_almost_equal(rtint[0], 0.1, decimal=6)
        npt.assert_almost_equal(rampl[0], 1.0, decimal=5)

    def test_two_open_periods(self, two_open_record):
        """[open, shut, open, shut] → two open periods."""
        itint, iampl, iprop = two_open_record
        rtint, rampl, rprop = impose_resolution(itint, iampl, iprop, tres=0.001)
        assert len(rtint) == 3  # open, shut, open
        assert rampl[0] != 0
        assert rampl[1] == 0
        assert rampl[2] != 0

    def test_short_shut_between_opens_lowers_running_amplitude(
        self, short_shut_between_opens
    ):
        """A short (unresolvable) SHUT between two same-amplitude opens shifts the
        running amplitude below the tolerance, causing a period break.

        The short shut contributes 0 to the accumulated amplitude-time product
        but increases the accumulated time, so atemp/ttemp < iampl of the next
        open → |difference| > AMPLITUDE_TOLERANCE → a new open period is started.

        This is correct and faithful to the Fortran original.  The fixture uses
        iampl=[1.0, 0.0, 1.0, 0.0]; the short 0.0 interval is a SHUT so it
        dilutes the running mean → two resolved open periods.
        """
        itint, iampl, iprop = short_shut_between_opens
        tres = 0.001
        rtint, rampl, rprop = impose_resolution(itint, iampl, iprop, tres=tres)
        # Two separate open periods (not merged) because running amplitude drops
        assert len(rtint) == 2
        # Total open time is conserved (50ms + 80ms; the short 0.1ms is absorbed)
        npt.assert_almost_equal(np.sum(rtint), 0.1301, decimal=4)

    def test_short_open_between_same_amplitude_opens(self):
        """A short (unresolvable) OPEN of the same amplitude IS merged.

        When the unresolvable interval is an open (not shut), atemp also
        increases proportionally → running amplitude stays constant →
        difference <= AMPLITUDE_TOLERANCE → one merged open period.
        """
        itint = np.array([0.05, 0.0001, 0.08, 0.04])
        iampl = np.array([1.0, 1.0, 1.0, 0.0])   # all opens have amplitude 1.0
        iprop = np.array([0, 0, 0, 0])
        rtint, rampl, rprop = impose_resolution(itint, iampl, iprop, tres=0.001)
        assert len(rtint) == 1
        npt.assert_almost_equal(rtint[0], 0.1301, decimal=4)

    def test_negative_interval_marked_bad(self):
        """Negative duration intervals must be silently marked unusable (not raise)."""
        itint = np.array([-0.001, 0.1, 0.05])
        iampl = np.array([1.0, 1.0, 0.0])
        iprop = np.array([0, 0, 0])
        # Should not raise; first interval is bad, processing starts at index 1
        rtint, rampl, rprop = impose_resolution(itint, iampl, iprop, tres=0.001)
        assert len(rtint) >= 1

    def test_badopen_flag(self):
        """Open interval longer than badopen must be flagged BAD (flag=8)."""
        from ekdist._constants import BAD_FLAG

        itint = np.array([1.0, 0.05])   # 1 s open, 50 ms shut
        iampl = np.array([1.0, 0.0])
        iprop = np.array([0, 0])
        rtint, rampl, rprop = impose_resolution(
            itint, iampl, iprop, tres=0.001, badopen=0.5
        )
        # The 1-s open should be flagged as bad
        assert rtint[0] == pytest.approx(1.0)
        assert rprop[0] == BAD_FLAG

    def test_simulated_flag(self):
        """For simulated records amplitude handling differs; must not raise."""
        itint = np.array([0.05, 0.0001, 0.08, 0.04])
        iampl = np.array([1.0, 0.0, 1.0, 0.0])
        iprop = np.array([0, 0, 0, 0])
        rtint, rampl, rprop = impose_resolution(
            itint, iampl, iprop, tres=0.001, is_simulated=True
        )
        assert len(rtint) >= 1


# =========================================================================== #
# AChsim.scn structural regression (no numeric reference yet)                  #
# =========================================================================== #

class TestAChSimStructural:
    """Structural properties that must hold for the AChsim.scn dataset.

    TODO: Replace with exact numeric regression once Fortran reference outputs
    are available (see module docstring TODO).
    """

    def test_resolved_count_less_than_raw(self, loaded_record):
        assert len(loaded_record.rtint) < len(loaded_record.itint)

    def test_starts_with_open(self, loaded_record):
        assert loaded_record.rampl[0] != 0.0

    def test_ends_with_open(self, loaded_record):
        assert loaded_record.rampl[-1] != 0.0

    def test_no_trailing_shuts(self, loaded_record):
        assert loaded_record.rampl[-1] != 0.0

    def test_periods_count_less_than_resolved(self, loaded_record):
        assert len(loaded_record.periods.intervals) <= len(loaded_record.rtint)

    def test_periods_alternates_open_shut(self, loaded_record):
        amps = loaded_record.periods.amplitudes
        for i in range(len(amps) - 1):
            is_open_i = amps[i] != 0
            is_open_next = amps[i + 1] != 0
            assert is_open_i != is_open_next, (
                f"Periods must alternate open/shut; failed at index {i}"
            )


# =========================================================================== #
# AChsim.scn numerical regression (golden-master at tres=30 µs, 2026-06-04)   #
# =========================================================================== #

class TestAChSimNumericalRegression:
    """Pin the exact impose_resolution output for AChsim.scn at tres=30 µs.

    Values were computed on 2026-06-04 from our Python implementation and serve
    as a golden-master regression guard.  Any future change to impose_resolution
    that alters these numbers must be deliberate and accompanied by an update
    to these constants.
    """

    # ---- expected counts ------------------------------------------------- #

    def test_raw_interval_count(self, loaded_record):
        assert len(loaded_record.itint) == 13948

    def test_resolved_interval_count(self, loaded_record):
        assert len(loaded_record.rtint) == 8565

    def test_resolved_open_count(self, loaded_record):
        open_mask = loaded_record.rampl != 0
        assert int(np.sum(open_mask)) == 4283

    def test_resolved_shut_count(self, loaded_record):
        shut_mask = loaded_record.rampl == 0
        assert int(np.sum(shut_mask)) == 4282

    def test_period_count(self, loaded_record):
        assert len(loaded_record.periods.intervals) == 8565

    def test_open_period_count(self, loaded_record):
        assert len(loaded_record.periods.open_intervals) == 4283

    def test_shut_period_count(self, loaded_record):
        assert len(loaded_record.periods.shut_intervals) == 4282

    # ---- first / last intervals ------------------------------------------ #

    def test_first_ten_durations(self, loaded_record):
        expected_t = np.array([
            4.0676165e-05, 1.161550368, 5.43031275e-04, 2.868956055,
            1.46274611e-04, 4.634056079, 4.87697683e-04, 1.19268e-04,
            1.735255003e-03, 3.184402588,
        ])
        npt.assert_almost_equal(loaded_record.rtint[:10], expected_t, decimal=6)

    def test_first_ten_amplitudes(self, loaded_record):
        expected_a = np.array([6., 0., 6., 0., 6., 0., 6., 0., 6., 0.])
        npt.assert_almost_equal(loaded_record.rampl[:10], expected_a, decimal=4)

    def test_last_three_durations(self, loaded_record):
        expected_t = np.array([8.9477e-05, 2.359118835, 3.83195e-04])
        npt.assert_almost_equal(loaded_record.rtint[-3:], expected_t, decimal=6)

    def test_last_interval_is_open(self, loaded_record):
        assert loaded_record.rampl[-1] != 0.0

    # ---- global statistics ----------------------------------------------- #

    def test_total_resolved_duration(self, loaded_record):
        """Total resolved duration must match golden value to 3 decimal places."""
        npt.assert_almost_equal(np.sum(loaded_record.rtint), 7683.308, decimal=3)

    def test_min_open_duration(self, loaded_record):
        open_mask = loaded_record.rampl != 0
        npt.assert_almost_equal(
            np.min(loaded_record.rtint[open_mask]), 30.013e-6, decimal=8
        )

    def test_max_open_duration(self, loaded_record):
        open_mask = loaded_record.rampl != 0
        npt.assert_almost_equal(
            np.max(loaded_record.rtint[open_mask]), 12.246324e-3, decimal=7
        )

    def test_max_shut_duration(self, loaded_record):
        shut_mask = loaded_record.rampl == 0
        npt.assert_almost_equal(
            np.max(loaded_record.rtint[shut_mask]), 18.486795, decimal=3
        )

    def test_mean_open_period(self, loaded_record):
        mean_ms = np.mean(loaded_record.periods.open_intervals) * 1e3
        npt.assert_almost_equal(mean_ms, 0.698800, decimal=3)

    def test_mean_shut_period(self, loaded_record):
        mean_ms = np.mean(loaded_record.periods.shut_intervals) * 1e3
        npt.assert_almost_equal(mean_ms, 1793.628, decimal=1)

    # ---- all flags must be 0 (AChsim has no bad intervals) --------------- #

    def test_all_flags_zero(self, loaded_record):
        assert np.all(loaded_record.rprop == 0)
